<?php 
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/main/include/prolog_before.php'); 
include("bm.php");
$arResult = Array (
    '0' => Array (
        'LID' => 'ru',
        'NAME' => 'Контент',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'content',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Контент',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '1',
                'CODE' => 'news',
                'NAME' => 'События и мероприятия',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '',
                'DETAIL_PAGE_URL' => '/events/#CODE#.html',
                'SECTION_PAGE_URL' => '',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Материалы',
                'ELEMENT_NAME' => 'Материал',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'MORE_PHOTO' => Array (
                        'NAME' => 'Фотографии',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'MORE_PHOTO',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'Y',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                ),
            ),
            '1' => Array (
                'ID' => '3',
                'CODE' => 'links',
                'NAME' => 'Полезные ссылки',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/content/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '#SITE_DIR#/content/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/content/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'LINK' => Array (
                        'NAME' => 'Ссылка',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'LINK',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                ),
            ),
            '2' => Array (
                'ID' => '21',
                'CODE' => 'info_materials',
                'NAME' => 'Информационные материалы',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '',
                'DETAIL_PAGE_URL' => '/informatsionnye-materialy/#SECTION_CODE#/#CODE#.html',
                'SECTION_PAGE_URL' => '/informatsionnye-materialy/#SECTION_CODE#/',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                ),
            ),
        ),
    ),
    '1' => Array (
        'LID' => 'ru',
        'NAME' => 'Финансово-хозяйственная деятельность',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'fin_hos',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Финансово-хозяйственная деятельность',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '14',
                'CODE' => 'gos_zadanie',
                'NAME' => 'Государственное задание',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/fin_hos/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/finansovo-khozyaystvennaya-deyatelnost/gosudarstvennoe-zadanie/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/fin_hos/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '1' => Array (
                'ID' => '15',
                'CODE' => 'plan_fin',
                'NAME' => 'План финансово-хозяйственной деятельности',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/fin_hos/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/finansovo-khozyaystvennaya-deyatelnost/plan-finansovo-khozyaystvennoy-deyatelnosti/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/fin_hos/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    '2' => Array (
        'LID' => 'ru',
        'NAME' => 'Общие сведения о поставщике социальных услуг',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'main_info',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Общие сведения о поставщике социальных услуг',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '2',
                'CODE' => 'company',
                'NAME' => 'Общие данные',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/main_info/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '#SITE_DIR#/main_info/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/main_info/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'TITLE' => Array (
                        'NAME' => 'Заголовок',
                        'ACTIVE' => 'Y',
                        'SORT' => '300',
                        'CODE' => 'TITLE',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'ADDRESS' => Array (
                        'NAME' => 'Адрес',
                        'ACTIVE' => 'Y',
                        'SORT' => '418',
                        'CODE' => 'ADDRESS',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'PHONE' => Array (
                        'NAME' => 'Тел.',
                        'ACTIVE' => 'Y',
                        'SORT' => '407',
                        'CODE' => 'PHONE',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'FAX' => Array (
                        'NAME' => 'Факс',
                        'ACTIVE' => 'Y',
                        'SORT' => '408',
                        'CODE' => 'FAX',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'EMAIL' => Array (
                        'NAME' => 'Email',
                        'ACTIVE' => 'Y',
                        'SORT' => '409',
                        'CODE' => 'EMAIL',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'NAME' => Array (
                        'NAME' => 'Полное наименование учреждения',
                        'ACTIVE' => 'Y',
                        'SORT' => '400',
                        'CODE' => 'NAME',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'SHORT_NAME' => Array (
                        'NAME' => 'Краткое наименование учреждения',
                        'ACTIVE' => 'Y',
                        'SORT' => '401',
                        'CODE' => 'SHORT_NAME',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'COMPANY_TYPE' => Array (
                        'NAME' => 'Тип организации',
                        'ACTIVE' => 'Y',
                        'SORT' => '402',
                        'CODE' => 'COMPANY_TYPE',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'MUNICIPAL_OBRAZOVANIE' => Array (
                        'NAME' => 'Муниципальное образование',
                        'ACTIVE' => 'Y',
                        'SORT' => '403',
                        'CODE' => 'MUNICIPAL_OBRAZOVANIE',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'DATE_REGISTRATION' => Array (
                        'NAME' => 'Дата гос. регистрации',
                        'ACTIVE' => 'Y',
                        'SORT' => '404',
                        'CODE' => 'DATE_REGISTRATION',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'UR_ADDRESS' => Array (
                        'NAME' => 'Юридический адрес',
                        'ACTIVE' => 'Y',
                        'SORT' => '405',
                        'CODE' => 'UR_ADDRESS',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'FACT_ADDRESS' => Array (
                        'NAME' => 'Фактический адрес',
                        'ACTIVE' => 'Y',
                        'SORT' => '406',
                        'CODE' => 'FACT_ADDRESS',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'INN' => Array (
                        'NAME' => 'ИНН ',
                        'ACTIVE' => 'Y',
                        'SORT' => '410',
                        'CODE' => 'INN',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'OGRN' => Array (
                        'NAME' => 'ОГРН ',
                        'ACTIVE' => 'Y',
                        'SORT' => '411',
                        'CODE' => 'OGRN',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'OKPO' => Array (
                        'NAME' => 'ОКПО ',
                        'ACTIVE' => 'Y',
                        'SORT' => '412',
                        'CODE' => 'OKPO',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'OKVD' => Array (
                        'NAME' => 'ОКВЭД ',
                        'ACTIVE' => 'Y',
                        'SORT' => '413',
                        'CODE' => 'OKVD',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'DIRECTOR' => Array (
                        'NAME' => 'Директор учреждения',
                        'ACTIVE' => 'Y',
                        'SORT' => '414',
                        'CODE' => 'DIRECTOR',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'ZAM_DIRECTOR' => Array (
                        'NAME' => 'Заместители директора',
                        'ACTIVE' => 'Y',
                        'SORT' => '415',
                        'CODE' => 'ZAM_DIRECTOR',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'UPALNAMOCH_ORGAN' => Array (
                        'NAME' => 'Уполномоченный территориальный орган',
                        'ACTIVE' => 'Y',
                        'SORT' => '416',
                        'CODE' => 'UPALNAMOCH_ORGAN',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'HTML',
                    ),
                    'MAP' => Array (
                        'NAME' => 'Как нас найти',
                        'ACTIVE' => 'Y',
                        'SORT' => '419',
                        'CODE' => 'MAP',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'map_yandex',
                    ),
                    'WORK_TIME' => Array (
                        'NAME' => 'График работы',
                        'ACTIVE' => 'Y',
                        'SORT' => '417',
                        'CODE' => 'WORK_TIME',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'Y',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => 'directory',
                    ),
                ),
            ),
            '1' => Array (
                'ID' => '4',
                'CODE' => 'kadrovoe_obespechenie',
                'NAME' => 'Кадровое обеспечение',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/main_info/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/obshchie-svedeniya/kadrovoe-obespechenie/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/main_info/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                ),
            ),
            '2' => Array (
                'ID' => '5',
                'CODE' => 'normativnaya-dokumentatsiya',
                'NAME' => 'Нормативная документация',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/main_info/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/obshchie-svedeniya/normativnaya-dokumentatsiya/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/main_info/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                ),
            ),
            '3' => Array (
                'ID' => '6',
                'CODE' => 'materialno_tekhnicheskoe_obespechenie_sotsialnykh',
                'NAME' => 'Материально-техническое обеспечение социальных услуг',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/main_info/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/obshchie-svedeniya/materialno-tekhnicheskoe-obespechenie-sotsialnykh-uslug/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/main_info/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '4' => Array (
                'ID' => '7',
                'CODE' => 'struktura',
                'NAME' => 'Структура и органы управления',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/main_info/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/obshchie-svedeniya/struktura-i-organy-upravleniya/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/main_info/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    '3' => Array (
        'LID' => 'ru',
        'NAME' => 'Получатели социальных услуг',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'poluchateli_sotsialnykh_uslug',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Получатели социальных услуг',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '10',
                'CODE' => 'Chislenost',
                'NAME' => 'Численность',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/poluchateli-sotsialnykh-uslug/chislennost/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '1' => Array (
                'ID' => '11',
                'CODE' => 'colischestvo_mest',
                'NAME' => 'Количество свободных мест',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/poluchateli-sotsialnykh-uslug/kolichestvo-svobodnykh-mest/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '2' => Array (
                'ID' => '12',
                'CODE' => 'obem_uslug',
                'NAME' => 'Объём предоставляемых социальных услуг',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/poluchateli-sotsialnykh-uslug/obyem-predostavlyaemykh-sotsialnykh-uslug/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '3' => Array (
                'ID' => '13',
                'CODE' => 'info_for_users',
                'NAME' => 'Информация для получателей социальных услуг',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/poluchateli-sotsialnykh-uslug/informatsiya-dlya-poluchateley-sotsialnykh-uslug/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/poluchateli_sotsialnykh_uslug/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    '4' => Array (
        'LID' => 'ru',
        'NAME' => 'Попечительский совет',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'popechitelsk_sovet',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Попечительский совет',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '18',
                'CODE' => 'pop_sovet',
                'NAME' => 'Попечительский совет',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/popechitelsk_sovet/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/popechitelskiy-sovet/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/popechitelsk_sovet/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    '5' => Array (
        'LID' => 'ru',
        'NAME' => 'Предписания органов государственного контроля и оценка качества',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'predpisania_organov',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Предписания органов государственного контроля и оценка качества',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '16',
                'CODE' => 'predpisania_organov',
                'NAME' => 'Предписания органов государственного контроля',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/predpisania_organov/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/predpisaniya-organov-gosudarstvennogo-kontrolya-i-otsenka-kachestva/predpisaniya-organov-gosudarstvennogo-kontrolya/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/predpisania_organov/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '1' => Array (
                'ID' => '17',
                'CODE' => 'nezavisimaia_ocenka',
                'NAME' => 'Независимая оценка качества оказанных социальных услуг',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/predpisania_organov/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/predpisaniya-organov-gosudarstvennogo-kontrolya-i-otsenka-kachestva/nezavisimaya-otsenka-kachestva-okazannykh-sotsialnykh-uslug/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/predpisania_organov/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    '6' => Array (
        'LID' => 'ru',
        'NAME' => 'Противодействие коррупции',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'protive_corup',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Противодействие коррупции',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '19',
                'CODE' => 'protiv_corupcii',
                'NAME' => 'Противодействие коррупции',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/protive_corup/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/protivodeystvie-korruptsii/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/protive_corup/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    '7' => Array (
        'LID' => 'ru',
        'NAME' => 'Служебные',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'service',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Служебные',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '22',
                'CODE' => 'feeback',
                'NAME' => 'Форма обратной связи',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/service/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '#SITE_DIR#/service/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/service/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'FIO' => Array (
                        'NAME' => 'Фио',
                        'ACTIVE' => 'Y',
                        'SORT' => '400',
                        'CODE' => 'FIO',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'Y',
                        'USER_TYPE' => '',
                    ),
                    'EMAIL' => Array (
                        'NAME' => 'Email',
                        'ACTIVE' => 'Y',
                        'SORT' => '401',
                        'CODE' => 'EMAIL',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'Y',
                        'USER_TYPE' => '',
                    ),
                    'PHONE' => Array (
                        'NAME' => 'Телефон',
                        'ACTIVE' => 'Y',
                        'SORT' => '402',
                        'CODE' => 'PHONE',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'QUESTION' => Array (
                        'NAME' => 'Вопрос',
                        'ACTIVE' => 'Y',
                        'SORT' => '403',
                        'CODE' => 'QUESTION',
                        'PROPERTY_TYPE' => 'S',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'Y',
                        'USER_TYPE' => 'HTML',
                    ),
                ),
            ),
        ),
    ),
    '8' => Array (
        'LID' => 'ru',
        'NAME' => 'Социальные услуги',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'sotsialnye_uslug',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            'ru' => Array (
                'NAME' => 'Социальные услуги',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'ID' => '8',
                'CODE' => 'formy_vidy_sotsialnykh_uslug',
                'NAME' => 'Формы и виды социальных услуг',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/sotsialnye_uslug/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/sotsialnye-uslugi/formy-i-vidy-sotsialnykh-uslug/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/sotsialnye_uslug/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
            '1' => Array (
                'ID' => '9',
                'CODE' => '',
                'NAME' => 'Тарифы на социальные услуги',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/sotsialnye_uslug/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '/sotsialnye-uslugi/formy-i-vidy-sotsialnykh-uslug/detail.php?ID=#ELEMENT_ID#detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/sotsialnye_uslug/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => 's1',
                ),
                'PROPS' => Array (
                    'DOC' => Array (
                        'NAME' => 'Документ',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'DOC',
                        'PROPERTY_TYPE' => 'F',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                    ),
                    'HIDE_NAME' => Array (
                        'NAME' => 'Скрыть название',
                        'ACTIVE' => 'Y',
                        'SORT' => '500',
                        'CODE' => 'HIDE_NAME',
                        'PROPERTY_TYPE' => 'L',
                        'MULTIPLE' => 'N',
                        'FILE_TYPE' => '',
                        'MULTIPLE_CNT' => '5',
                        'LINK_IBLOCK_ID' => '0',
                        'IS_REQUIRED' => 'N',
                        'USER_TYPE' => '',
                        'VALUES' => Array (
                            '0' => Array (
                                'VALUE' => 'ДА',
                                'DEF' => 'N',
                                'SORT' => '500',
                                'EXTERNAL_ID' => 'YES',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);
$bm = new BitrixMigration(__FILE__);
$bm->sStoreFilesDir = '/bm_files/';
$bm->uploadArray($arResult);
?>